unit SSLExporter;

interface

uses
   System.SysUtils, System.Classes, uDialogueTypes;

type
  TSSLExporter = class
  public
    class function ExportProject(AProject: TDialogueProject; const AFilePath: string): Boolean;
  end;

implementation

{ TSSLExporter }

class function TSSLExporter.ExportProject(AProject: TDialogueProject; const AFilePath: string): Boolean;
var
  Lines: TStringList;
  Node: TDialogueNode;
  I, OptMsgNum, NodeMsgNum: Integer;
  procedure AddOpt(optType: string; reaction, msgNum: Integer; targetNodeID: string);
  begin
    Lines.Add(Format('  %s(%d, %s, %d);', [optType, msgNum, targetNodeID, reaction]));
  end;
begin
  Result := False;
  Lines := TStringList.Create;
  try
    Lines.Add('/* Generated by Fallout Dialogue Creator */');
    Lines.Add('');

    // start procedure
    Lines.Add('procedure start begin');
    if AProject.StartNodeID <> '' then
      Lines.Add(Format('  call %s;', [AProject.StartNodeID]))
    else if AProject.Nodes.Count > 0 then
      Lines.Add(Format('  call %s;', [AProject.Nodes[0].ID]));
    Lines.Add('end');
    Lines.Add('');

    NodeMsgNum := 100;
    OptMsgNum := 500;

    for Node in AProject.Nodes do
    begin
      if Node.NodeType = ntEndDialogue then
        Continue;

      Lines.Add(Format('procedure %s begin', [Node.ID]));

      if Node.Text <> '' then
      begin
        Lines.Add(Format('  Reply(%d);', [NodeMsgNum]));
        Inc(NodeMsgNum);
      end;

      if Node.PlayerOptions.Count > 0 then
      begin
        for I := 0 to Node.PlayerOptions.Count - 1 do
        begin
          if Node.PlayerOptions[I].HasSkillCheck then
            AddOpt('BOption', -4, OptMsgNum, Node.PlayerOptions[I].TargetNodeID)
          else if I = 0 then
            AddOpt('NOption', -4, OptMsgNum, Node.PlayerOptions[I].TargetNodeID)
          else
            AddOpt('NOption', 4, OptMsgNum, Node.PlayerOptions[I].TargetNodeID);
          Inc(OptMsgNum);
        end;
      end;

      Lines.Add('end');
      Lines.Add('');
    end;

    // Node998 — combat node
    Lines.Add('procedure Node998 begin');
    Lines.Add('  set_hostile;');
    Lines.Add('end');
    Lines.Add('');

    // Node999 — end dialogue node
    Lines.Add('procedure Node999 begin');
    Lines.Add('end');

    Lines.SaveToFile(AFilePath, TEncoding.UTF8);
    Result := True;
  finally
    Lines.Free;
  end;
end;

end.