unit SSLExporter;

interface

uses
   System.SysUtils, System.Classes, System.TypInfo, uDialogueTypes, SkillCheckSystem;

type
  TSSLExporter = class
  public
    class function ExportProject(AProject: TDialogueProject; ASkillManager: TSkillCheckManager; const AFilePath: string): Boolean;
  end;

implementation

{ TSSLExporter }

class function TSSLExporter.ExportProject(AProject: TDialogueProject; ASkillManager: TSkillCheckManager; const AFilePath: string): Boolean;
var
  Lines: TStringList;
  Node: TDialogueNode;
  Check: TSkillCheck;
  I: Integer;
  MsgLineNum: Integer;
var
  StartNodeID: string;
begin
  Result := False;
  Lines := TStringList.Create;
  try
    Lines.Add('/* Generated by Fallout Dialogue Creator */');
    Lines.Add('procedure start begin');
    if AProject.StartNodeID <> '' then
      StartNodeID := AProject.StartNodeID
    else if AProject.Nodes.Count > 0 then
      StartNodeID := AProject.Nodes[0].ID
    else
      StartNodeID := 'Node001';
    Lines.Add(Format('  call %s;', [StartNodeID]));
    Lines.Add('end');
    Lines.Add('');

    MsgLineNum := 100;
    for Node in AProject.Nodes do
    begin
      if Node.NodeType = ntEndDialogue then
        Continue;

      Lines.Add(Format('procedure %s begin', [Node.ID]));
      if Node.Text <> '' then
      begin
        Lines.Add(Format('  Reply(%d);', [MsgLineNum]));
        Inc(MsgLineNum);
      end;

      // Handle skill checks
      Check := ASkillManager.FindCheckByNode(Node.ID);
      if Assigned(Check) then
      begin
        Lines.Add(Format('  if (skill_check(dude_obj, %s, %d) > 0) then begin',
          [GetEnumName(TypeInfo(TSkillType), Integer(Check.Skill)), Check.Difficulty]));
        if Check.SuccessNodeID <> '' then
          Lines.Add(Format('    call %s;', [Check.SuccessNodeID]));
        Lines.Add('  end else begin');
        if Check.FailureNodeID <> '' then
          Lines.Add(Format('    call %s;', [Check.FailureNodeID]));
        Lines.Add('  end');
      end
      else
      begin
        // Add giq_option for player replies
        for I := 0 to Node.PlayerOptions.Count - 1 do
          Lines.Add(Format('  giq_option(4, NAME, %d, %s, NEUTRAL_REACTION);', [MsgLineNum + I, Node.PlayerOptions[I].TargetNodeID]));
      end;

      Lines.Add('end');
      Lines.Add('');
    end;

    Lines.SaveToFile(AFilePath, TEncoding.UTF8);
    Result := True;
  finally
    Lines.Free;
  end;
end;

end.